repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint && make lint-type
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_filenames: false

      - id: fmt-check
        name: fmt-check
        entry: make fmt-check
        language: system
        types: [python]
        files: pyproject\.toml|\.py$
        pass_filenames: false