name: ci (fmt, lint, test)

on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Use Cargo to install rye
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: cargo install --git https://github.com/mitsuhiko/rye

      - name: Sync Python environment
        run: rye sync

      - name: Run fmt check
        run: make fmt-check
        
      - name: Run lint
        run: make lint && make lint-type

      - name: Run tests
        run: make test

      # bench for lols
      - name: Run bench
        run: make bench
