name: fmt-check

on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci-fmt.yaml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci-fmt.yaml'

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Use Cargo to install rye
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: cargo install --git https://github.com/mitsuhiko/rye -branch main

      - name: Sync Python environment
        run: rye sync

      - name: Run fmt check
        run: make fmt-check
        
      - name: Run lint
        run: make lint && make lint-type

      - name: Run tests
        run: make test
