name: ci (fmt, lint, test)

on:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yaml'

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Use Cargo to install rye
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: cargo install --git https://github.com/mitsuhiko/rye

      - name: Sync Python environment
        run: rye sync

      - name: Run fmt check
        run: |
          rye run ruff check . --select I
          rye run black . --check
        
      - name: Run lint
        run: |
          rye run mypy src tests
          rye run ruff check . --select-extend I

      - name: Run tests
        run: rye run pytest

      - name: Run bench
        run: rye run python tests/bench/excel_io.py
